[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    buildCommand = "next build"
    publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "next dev"
  targetPort = 3000
  publish = ".next"
  port = 3000
