[build]
  # Use the standard Next.js build command
  command = "next build && next export"
  # The output directory for static export
  publish = "out"

[build.environment]
  # Use LTS version of Node.js
  NODE_VERSION = "18.18.2"
  NPM_VERSION = "9.8.1"
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  # Enable static export
  NEXT_EXPORT = "true"
  # Disable server components
  NEXT_DISABLE_SERVER_COMPONENTS = "true"

[context.production.environment]
  NODE_ENV = "production"
  # Enable production optimizations
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects configuration for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Development server configuration
[dev]
  command = "next dev"
  port = 3000
  publish = ".next"
  targetPort = 3000
