[build]
  # Install dependencies and build the project
  command = "npm install && npm run build && npm run export"
  # The output directory for static export
  publish = "out"

[build.environment]
  # Use LTS version of Node.js
  NODE_VERSION = "18.18.2"
  NPM_VERSION = "9.8.1"
  
  # Next.js configuration
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  
  # Build optimizations
  GENERATE_SOURCEMAP = "false"
  
  # Install babel-loader and required plugins
  NPM_FLAGS = "--legacy-peer-deps"

# Production environment settings
[context.production]
  command = "npm run build && npm run export"
  
  [context.production.environment]
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"

# Redirects configuration for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Development server configuration
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  targetPort = 3000
